// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project9_cohort4.Server.Models;

#nullable disable

namespace project9_cohort4.Server.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("project9_cohort4.Server.Models.AdoptionApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApplicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId")
                        .HasName("PK__Adoption__C93A4C99FFEC99D8");

                    b.HasIndex("AnimalId");

                    b.HasIndex("UserId");

                    b.ToTable("AdoptionApplications");
                });

            modelBuilder.Entity("project9_cohort4.Server.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<string>("AdoptionStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Available");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SpecialNeeds")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Temperament")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("AnimalId")
                        .HasName("PK__Animals__A21A7307727FCE24");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("project9_cohort4.Server.Models.Shelter", b =>
                {
                    b.Property<int>("ShelterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShelterId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShelterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ShelterId")
                        .HasName("PK__Shelters__E2CDF5546EC5EA4D");

                    b.ToTable("Shelters");
                });

            modelBuilder.Entity("project9_cohort4.Server.Models.ShelterAnimal", b =>
                {
                    b.Property<int>("ShelterAnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShelterAnimalId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.HasKey("ShelterAnimalId")
                        .HasName("PK__ShelterA__28908D34344C5F85");

                    b.HasIndex("AnimalId");

                    b.HasIndex("ShelterId");

                    b.ToTable("ShelterAnimals");
                });

            modelBuilder.Entity("project9_cohort4.Server.Models.SuccessStory", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoryId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("StoryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("StoryText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StoryId")
                        .HasName("PK__SuccessS__3E82C048F6DBE715");

                    b.HasIndex("AnimalId");

                    b.HasIndex("UserId");

                    b.ToTable("SuccessStories");
                });

            modelBuilder.Entity("project9_cohort4.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C19EDAB47");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4585A1460")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053403862BC9")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("project9_cohort4.Server.Models.AdoptionApplication", b =>
                {
                    b.HasOne("project9_cohort4.Server.Models.Animal", "Animal")
                        .WithMany("AdoptionApplications")
                        .HasForeignKey("AnimalId")
                        .IsRequired()
                        .HasConstraintName("FK__AdoptionA__Anima__45F365D3");

                    b.HasOne("project9_cohort4.Server.Models.User", "User")
                        .WithMany("AdoptionApplications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__AdoptionA__UserI__44FF419A");

                    b.Navigation("Animal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project9_cohort4.Server.Models.ShelterAnimal", b =>
                {
                    b.HasOne("project9_cohort4.Server.Models.Animal", "Animal")
                        .WithMany("ShelterAnimals")
                        .HasForeignKey("AnimalId")
                        .IsRequired()
                        .HasConstraintName("FK__ShelterAn__Anima__52593CB8");

                    b.HasOne("project9_cohort4.Server.Models.Shelter", "Shelter")
                        .WithMany("ShelterAnimals")
                        .HasForeignKey("ShelterId")
                        .IsRequired()
                        .HasConstraintName("FK__ShelterAn__Shelt__5165187F");

                    b.Navigation("Animal");

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("project9_cohort4.Server.Models.SuccessStory", b =>
                {
                    b.HasOne("project9_cohort4.Server.Models.Animal", "Animal")
                        .WithMany("SuccessStories")
                        .HasForeignKey("AnimalId")
                        .IsRequired()
                        .HasConstraintName("FK__SuccessSt__Anima__4AB81AF0");

                    b.HasOne("project9_cohort4.Server.Models.User", "User")
                        .WithMany("SuccessStories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__SuccessSt__UserI__49C3F6B7");

                    b.Navigation("Animal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project9_cohort4.Server.Models.Animal", b =>
                {
                    b.Navigation("AdoptionApplications");

                    b.Navigation("ShelterAnimals");

                    b.Navigation("SuccessStories");
                });

            modelBuilder.Entity("project9_cohort4.Server.Models.Shelter", b =>
                {
                    b.Navigation("ShelterAnimals");
                });

            modelBuilder.Entity("project9_cohort4.Server.Models.User", b =>
                {
                    b.Navigation("AdoptionApplications");

                    b.Navigation("SuccessStories");
                });
#pragma warning restore 612, 618
        }
    }
}
